CREATE TABLE IF NOT EXISTS volume (
    date DATE NOT NULL,
    symbol TEXT NOT NULL,
    volume INTEGER NOT NULL,
    AV30 INTEGER,
    AV20 INTEGER,
    AV15 INTEGER,
    AV10 INTEGER,
    AV5 INTEGER,
    ACV30 INTEGER,
    ACV20 INTEGER,
    ACV15 INTEGER,
    ACV10 INTEGER,
    ACV5 INTEGER,
    UNIQUE (date, symbol)
);